title: TETON Cardano Stake Pool
email: info@rockinghat.com
description:
  ADA holders are incentivized to stake their tokens to secure the Cardano blockchain, while receiving a reward in return. Delegate your ADA to the TETON satke pool, and earn ADA rewards.
baseurl: "" # the subpath of your site, e.g. /blog
domain: "teton.rockinghat.com"
url: "https://teton.rockinghat.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: RockingHatLLC
github_username:  rockinghat

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

destination: docs/
